version: '3.9'
services:
  kong-database:
    image: postgres:13
    restart: always # Always start every time 
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "$KONG_DATABASE_LOCAL_PORT:$KONG_DATABASE_DOCKER_PORT"

  kong-migration:
    image: kong/kong-gateway:3.10
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      - KONG_DATABASE=$KONG_DATABASE
      - KONG_PG_DATABASE=$KONG_PG_DATABASE
      - KONG_PG_PASSWORD=$KONG_PG_PASSWORD
      - KONG_PG_HOST=$KONG_PG_HOST
    links:
      - kong-database # The connection is kong-database Service 
    depends_on:
      - kong-database # Depend on kong-database service 

  kong-gateway:
    image: kong/kong-gateway:3.10  
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: $KONG_DATABASE
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_USER: $KONG_PG_USER
      KONG_PG_PASSWORD: $KONG_PG_PASSWORD
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
    depends_on:
      - kong-migration
    links:
      - kong-database  
    ports: 
      - 8000:8000 
      - 8443:8443 
      - 8001:8001 
      - 8444:8444 
      - 8002:8002 
      - 8445:8445 
      - 8003:8003 
      - 8004:8004 

networks:
  kong-net:
    driver: bridge

  
